### ISSUE TITLE
issue loading jar

### ISSUE THREAD

**Issue by babarlelephant** [leaningtech/cheerpj-meta#123]
Hi, with the standard codes  the error messages are impossible to understand,  it is either trying to load figtree.jar which doesn't exist or failing with (Error: An unexpected error occurred while trying to open file /app/figtree.jar.js)

Can you tell me if this jar.js loads and if so with which code?

http://www.paris8.free.fr/figtree.jar.js

The main class is figtree.application.FigTreeApplication

Its name should be N7figtree11application18FigTreeApplicationX in the js.
The jar it comes from works fine with java -jar figtree.jar

**Comment by marsicplusplus** [comment]
You still need the the .jar to run the application even if it´s already been converted with cheerpj.

Maybe I misunderstood, but I guess you are trying to run the .jar.js as a simple javascript file. If that´s the case please, refer to the tutorial here to learn how to run java application in the browser trough cheerpj: https://github.com/leaningtech/cheerpj-meta/wiki/Tutorial

If I´m getting it wrong please, clarify your issue so that I can assist you further.

**Comment by babarlelephant** [comment]
Thanks a lot, I feel very dumb. Why do you explain those things clearly? Your demo and tutorial pages are really not adapted to your great work. You need to explain in a few words what cheerpj is doing, what the js file contains, and how to load the jar and call a method from it, and the error messages we can hope to obtain when something fail.
