### ISSUE TITLE
Uncaught (in promise) 

### ISSUE THREAD

**Issue by ethanaobrien** [leaningtech/cheerpj-meta#127]
[localhost-1619814167315.log](https://github.com/leaningtech/cheerpj-meta/files/6407864/localhost-1619814167315.log)
Console log above.

I am on chrome os
Trying to run opsu: package name itdelatrisu.opsu.Opsu

**Comment by marsicplusplus** [comment]
Hi @ethanaobrien, 

I was able to reproduce the issue and to locate the bug.
It seems to be related to another problem we already have in our backlog and on which we should start to work on soon.

Thanks for the taking the time to report this to us, we will use this as a testcase as well and we´ll notify when this is solved.

**Comment by marsicplusplus** [comment]
Is this the original Minecraft .jar file? I'm not able to run this with "desktop java" either.

In any case, Minecraft won't work in CheerpJ as it uses JNI methods that are not implemented in CheerpJ for rendering 3D graphics.
Implementing those JNI methods in CheerpJ is no currently in our plans.

**Comment by ethanaobrien** [comment]
@marsicplusplus That is understandable. I also do not think that this issue should be closed (yet) because my problem is itdelatrisu.opsu.Opsu. I just got a similar error with another file and was asking to see if it might be the same thing.

**Comment by gl91306** [comment]
ive worked a bit more on this, and ive got the .minecraft folder and yoinked the libs and classes and everything to make it launch without the launcher

**Comment by gl91306** [comment]
[https://replit.com/@Tedisc00l/PowerfulBogusCable](https://replit.com/@Tedisc00l/PowerfulBogusCable) here it is. You have to start a python server with `python3 -m http.server` first to serve the files. it gets as far as initializing the graphics, but of course, since lwjgl is a native jni thing, it wont launch. to combat this, ive tried to implement the native methods for lwjgl myself. As seen here, the template for native methods was generated, and i managed to fill one file up.
![Screenshot 2021-11-17 10 34 55 AM](https://user-images.githubusercontent.com/75343148/142261453-6e4d0504-aa49-4a81-ac92-14070bea0118.png)
i then thought everything would go smoothly, becuase all i would have to do would be to change all the opengl parts to webgl. I then realized I wouldn't know how to fill most of the methods, so i looked in to cheerp to compile the c files [here](https://github.com/LWJGL/lwjgl/tree/master/src/native) i got preety far, but i got an error ;-;. here is my progres in doing so: [here](https://replit.com/@Tedisc00l/PowerfulBogusCable#comman) If you want to try it yourself you can.
