### ISSUE TITLE
(feature req) option of usage of jor1k networking relay for network connections

### ISSUE THREAD

**Issue by ayunami2000** [leaningtech/cheerpj-meta#130]
as used in [jor1k](https://s-macke.github.io/jor1k/), [v86](https://copy.sh/v86/), and [jslinux](https://bellard.org/jslinux/), the networking relay is great for network connections from the browser. please consider implementing it to cheerpj (it also solves cross origin issues!!)

the public relay is at `relay.widgetry.org` and the source for it (including how it works) is at https://github.com/benjamincburns/websockproxy

**Comment by alexp-sssup** [comment]
We now support networking via Tailscale. We cannot directly provide a relay for users, due to the risk of abuse, but via Tailscale each user can integrate networking as they see fit. This includes offering internet access to visitors of the page if deemed safe for the specific use case.

For more information: https://labs.leaningtech.com/cheerpj3/guides/Networking#generalized-networking
