### ISSUE TITLE
Single javascript file?

### ISSUE THREAD

**Issue by norzak** [leaningtech/cheerpj-meta#17]
I see there is a loader.js that loads all the required modules. Would it be possible to merge all into one single Javascript file removing the methods and classes that are not used from the merged modules?

**Comment by alexp-sssup** [comment]
We split the Java runtime into modules by default to minimize the amount of code which is downloaded by the application. Due to the dynamic nature of the Java language it is not truly possible to statically resolve all needed classes. At runtime, by using reflection, any class can be loaded. One of the unique advantages of CheerpJ is indeed full support for Java reflection, no other Java to JS tool supports this.

To improve load time performance we are we are working on an API to allow an application to ‘preload’ a predefined list of Java modules. Those can then be later used as part of the application with no need of downloading them on the fly. You will be able to tailor this list to your specific application.

In terms of download time, size and execution time performance, this solution will get you very close to having a single file with the application dependencies.
