### ISSUE TITLE
How about the keystrokes

### ISSUE THREAD

**Issue by neoedmund** [leaningtech/cheerpj-meta#194]
Wow, quite impressive about the Java Swing support. 
I can even run neoeedit.jar after recompile with jdk 8.
But some keys are go through to the web browser, like, ,<kbd>TAB</kbd> , <kbd>ctrl-H</kbd>, ... ,<kbd> del</kbd>, <kbd>backspace</kbd>, ...
any options?

**Comment by alexp-sssup** [comment]
There is an optional `cheerpjInit` callback that let the user decides which additional shortcuts should be handled by Java rather than the browser: https://labs.leaningtech.com/cheerpj3/reference/cheerpjInit#overrideshortcuts

We do not automatically `preventDefault` all shortcuts since that would hijack legitimate ones that the user of the page might need. With the aforementioned callback the page author can refine the behavior.

**Comment by neoedmund** [comment]
after using ```
 await cheerpjInit({
         overrideShortcuts: function (e) {return true;}
        });
```
I cannot input a single character, something wrong?
I suppose to have as many keys as possible because it's a text editor app.

**Comment by neoedmund** [comment]
still impressive job, thank you!
