### ISSUE TITLE
How to convert an applet?

### ISSUE THREAD

**Issue by jsfan3** [leaningtech/cheerpj-meta#2]
I have this code:
```
<applet code="CabriJava.class" width="200" height="250" align="top" archive="CabriJava.jar" border="0" alt="seno">
        <param name="lang" value="it">
        <param name="file" value="sen.fig.class">
        <param name="bgcolor" value="#FFFFFF">
      </applet> 
```
How can I convert it to javascript?

I tried the following command:
~/cheerpj_preview/cheerpjfy.py CabriJava.jar 

```
Traceback (most recent call last):
  File "/home/francesco/cheerpj_preview/cheerpjfy.py", line 384, in <module>
    runOnDir(tempDir);
  File "/home/francesco/cheerpj_preview/cheerpjfy.py", line 311, in runOnDir
    classPath = getManifestProperty(jarFile, "Class-Path");
  File "/home/francesco/cheerpj_preview/cheerpjfy.py", line 288, in getManifestProperty
    m = jarFile.open("META-INF/MANIFEST.MF")
  File "/usr/lib/python3.5/zipfile.py", line 1255, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python3.5/zipfile.py", line 1199, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'META-INF/MANIFEST.MF' in the archive"
```

The applet java is published inside this simple page:
https://www.storia-matematica.net/interattivo_09.htm

This is the link to the jar:
https://www.storia-matematica.net/CabriJava.jar

**Comment by reportmill** [comment]
It looks like you might need to repackage the jar to get a manifest file and or META-INF. I was able to get the jar to compile by repackaging like this:

	> mkdir test
	> mkdir test/jar_files
	> cd test/jar_files
	> curl -O https://www.storia-matematica.net/CabriJava.jar <https://www.storia-matematica.net/CabriJava.jar>
	> jar xf CabriJava.jar
	> rm CabriJava.jar
	> jar cf ../CabriJava.jar *
	> cd ..
	> python3 /Temp/tools/cheerpj/cheerpjfy.py CabriJava.jar

I put a test up here, and it runs, but it doesn’t seem to be finding the "figure file”.

	http://reportmill.com/cj/CabriJava/ <http://reportmill.com/cj/CabriJava/> (don’t forget to run the applet with the applet runner).

You might consider converting the app to run in a JFrame instead of JApplet. I think it’s a better runtime experience - particularly since you don’t have to trigger the applet runner.

Also, as of today, there is a new CheerpJ developer group <https://groups.google.com/forum/#!forum/cheerpj-developers> at Google Groups - I think that might be a better place for developer questions moving forward.

jeff

**Comment by alexp-sssup** [comment]
Please take a look here: https://github.com/leaningtech/cheerpj-meta/wiki/Getting-Started#converting-an-applet
