### ISSUE TITLE
Java Applets

### ISSUE THREAD

**Issue by pachuco** [leaningtech/cheerpj-meta#35]
Is it possible for embedded cheerpj runtime to run java Applets in a webpage without the use of the Chrome extension?

**Comment by pachuco** [comment]
To answer my own question.

`
cheerpjInit();
var applet = Document.getElementById("applet");
cheerpjRewriteAndReplaceApplet(applet); 
`

**Comment by alexp-sssup** [comment]
It is even simpler, just run ```cheerpjInit()```, the system will take care of finding and replacing the applet on the page. Please note that current the system only look for one applet tag per page, this limitation will be fixed in the future.

This is documented here: https://github.com/leaningtech/cheerpj-meta/wiki/Getting-Started#converting-an-applet
