### ISSUE TITLE
Writing /files/ fails

### ISSUE THREAD

**Issue by gtamas** [leaningtech/cheerpj-meta#47]
For some reason, the Java program can't write any data to /files/ FS.

Everything seems to work fine up to the point where I call this Java method:

```
  public void postsign(byte[] signature) throws IOException {
    OutputStream signedStream = new FileOutputStream("/files/signed.pdf");
    SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.getAlgorithm(this.padesParams.getEncryptionAlgorithm(),
      this.padesParams.getDigestAlgorithm());
    SignatureValue signatureValue = new SignatureValue(signatureAlgorithm, signature);
    DSSDocument signedDocument = this.service.signDocument(this.doc, this.padesParams, signatureValue);

    signedDocument.writeTo(signedStream);
  }
```

I'm calling this from JS using:

```
const sig = cjTypedArrayToJava(signature);
cjCall(someClassInstance, 'postsign',sig);
```

There is no error. The promise reports success. Even the output file "/signed.pdf" appears in IndexedDB, but its empty. This is what I get:  

{type: file, contents: null, inodeId: someNumber}

What could be wrong?

All other operations before this one return with success, I see no errors.

**Comment by gtamas** [comment]
By the way the Java function I'm calling here worked totally fine before.
When I just passed all input arguments to Main() and the whole code was Java, this same function was able to write the output successfully. 
But now I'm trying to implement all the Main() method's functionality in JS b calling Java methods using cjCall / cjNew. Main is now an empty method. 

Somehow calling the same stuff from JS doesn't seem to work, but I don't understand why.

**Comment by alexp-sssup** [comment]
Please attach a fully reproducible test case, otherwise it is very hard for us to understand what is happening.

Moreover, you have to be careful when inspecting the IndexedDB contents directly from JS or from the dev tools. CheerpJ only commits the data to the IndexedDB after the file descriptor is closed, so although you can read the data from inside CheerpJ it will not appear directly in the DB.

You should try to manually close the FileOutputStream to force a flush of the data.

**Comment by gtamas** [comment]
Hi

Thank you, force flush solved it. All I had to add was:

```
signedStream.flush();
signedStream.close();
```

Now everything works :)
