### ISSUE TITLE
I always get the following errors in my console.

### ISSUE THREAD

**Issue by Zezal2** [leaningtech/cheerpj-meta#68]
![error](https://user-images.githubusercontent.com/49757920/56368731-16e75d80-6209-11e9-9a69-ef9e317aee5e.png)

**Comment by yuri91** [comment]
Hi!

It would be helpful to have some more information:

- Can you share the code that you are trying to run, or in alternative forge a testcase that reproduces your problem?
- Which version of Cheerpj are you using, and which version of the runtime?

Thanks

**Comment by Zezal2** [comment]
Good evening,

I am trying to run a java application on a browser. Please find attached
the jar file as well as the .rar containing the application I am using
below. The current version is cheerpj 1.3 as well as the runtime I guess. I
would be grateful if you could help me with this one. Also, take note that
I am currently a student and, in my learning phase, the application is only
for learning purposes. kind regards.

 Youpi, The lost gecko.jar
<https://drive.google.com/file/d/1M_oCBqNxgdkDry4ZUcTDJROjB7fGYqm_/view?usp=drive_web>

 geckoGame
<https://drive.google.com/drive/folders/15Pn1k6gRwmRk1uIS4qTx8uRoqq-ojm_e>

**Comment by alexp-sssup** [comment]
I can see that there is an error in the way the ```cheerpjRunJar``` is used. This is the code in your ```index.html```

```
      cheerpjInit();
      cheerpjCreateDisplay(800,600);
      cheerpjRunJar("/app/../geckoGame/cheerpj/TextDemo.jar"); 
```

CheerpJ implements a virtual file system with multiple mount points (see here for more information https://github.com/leaningtech/cheerpj-meta/wiki/File-System-support). The ```/app/``` mount point is used for files relative to the page and retrieved over HTTP.

The path ```/app/../geckoGame/cheerpj/TextDemo.jar``` is not a valid path in the CheerpJ filesystem (it would resolve to ```/geckoGame/cheerpj/TextDemo.jar```).

The fix is very simple:

1. Run a local web server, such as node.js ```http-server``` in the directory where the index.html file is
2. Use the ```cheerpjRunJar("/app/TextDemo.jar");```
3. Access the page as http://127.0.0.1:8080/index.html (or whatever port the server is using)

Or follow the instructions here:
https://github.com/leaningtech/cheerpj-meta/wiki/Getting-Started#basic-html-page-for-testing
