### ISSUE TITLE
com.leaningtech.client.EventListener interface is missing a handle method

### ISSUE THREAD

**Issue by renatoathaydes** [leaningtech/cheerpj-meta#69]
It seems to be currently impossible to set a click handler on a html element.

That's because the `EventListener` interface is empty. So there's no way to implement any method.

One would expect `EventListener` to look as follows:

```java
@FunctionalInterface
public interface EventListener
{
    void handle( MouseEvent event );
}
```

So, it could be implemented with a lambda:

```java
element.set_onclick( event -> accept( true ) );
```

Note: please stop using underscore on method names. In Java, the convention is to use `setOnClick()`, not `set_onclick()`.

**Comment by alexp-sssup** [comment]
It is indeed currently impossible to directly set event handlers for DOM events from Java. You can easily work around this problem by adding the handlers on the JS side, and then using CheerpJ interoperability API to execute Java code via ```cjCall``` or ```cjNew```. See here for more information: https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API#cjcall--cjnew

Although I understand your point that the setters/getters convention is not consistent with Java styling, it is not worthwhile for us to make those nicer right now. We plan to eventually remove those in favor of simpler Java field access style.

```
obj.set_onclick(...) -> obj.onclick = ...
obj.get_onclick() -> obj.onclick.
```

In general DOM access from CheerpJ is currently at the MVP stage due to low demand from commercial users. As we are a small company we need to prioritize features which have immediate adoption.
