### ISSUE TITLE
> No, you need python 3.

### ISSUE THREAD

**Issue by ruthwickbabu** [leaningtech/cheerpj-meta#75]
> No, you need python 3.

Thanks for the help and Information

_Originally posted by @ruthwickbabu in https://github.com/leaningtech/cheerpj-meta/issues/74#issuecomment-553343271_

**Comment by alexp-sssup** [comment]
Could you elaborate on what is the problem with the python 3 dependency?

**Comment by ruthwickbabu** [comment]
I downloaded and Installed both Cheerpj and Phython3 ,  While running is Showing. Please refer to the below pic. 
![Capture1](https://user-images.githubusercontent.com/53474430/68844054-266f4c00-06ef-11ea-9b01-b1dd019cb832.JPG)

**Comment by yuri91** [comment]
Hi @ruthwickbabu !

The command you are trying to run should be typed in the Windows Command Prompt, not in the python interactive shell.

**Comment by ruthwickbabu** [comment]
> Hi @ruthwickbabu !
> 
> The command you are trying to run should be typed in the Windows Command Prompt, not in the python interactive shell.

Yeah! I did like that too but is Showing no Such file or directory.

**Comment by yuri91** [comment]
Make sure that the arguments you are giving to the `py` command refer to files that actually exist on your filesystem.

The arguments are the path to the `cheerpjfy.py` script (which should be wherever you extracted the zip file containing cheerpj) and the path to the jar file of your application.

The ones you are using seem taken from an example: is your username "UserName" and your jar "application.jar" ?

**Comment by ruthwickbabu** [comment]
> Make sure that the arguments you are giving to the `py` command refer to files that actually exist on your filesystem.
> 
> The arguments are the path to the `cheerpjfy.py` script (which should be wherever you extracted the zip file containing cheerpj) and the path to the jar file of your application.
> 
> The ones you are using seem taken from an example: is your username "UserName" and your jar "application.jar" ?

Once Check here
![Capture](https://user-images.githubusercontent.com/53474430/68856294-2cbcf280-0706-11ea-95dc-f3f185eb3eb7.JPG)

**Comment by alexp-sssup** [comment]
@ruthwickbabu They path you are using is clearly mixed-up, there is a reference the a ```python-3.8.0-embed-amd64``` directory which should not be there.

We cannot tell you the exact paths you have to write since we don't know the layout of your file system.

Take the time to familiarize yourself with the windows command prompt and verify that the paths you are using are correct.

My advice would be to split the problem in 2 steps

1) Identify the path for the ```cheerpjfy.py```, you can call the script with the ```-v``` option to only show the current version. When you achieve that you can move to the second step
2) Identify the path for the JAR files that you want to convert and call ```cheerpjfy.py``` on that path

I am closing this bug, since there is nothing wrong with CheerpJ and it's just a matter of correctly invoking a command line program on Windows. Please open a new issue if there is an actual problem with CheerpJ.
