### ISSUE TITLE
LinkError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by lilin12123** [leaningtech/cheerpj-meta#81]
Hi, when I try to the TextDemo.jar using the script below
```
  <script>
      cheerpjInit({disableErrorReporting:true});
      cheerpjCreateDisplay(1200,800);
      cheerpjRunJar("TextDemo","http://127.0.0.1:8080/TextDemo.jar"); 
  </script>
```
It outputs the error:
```
LinkError: WebAssembly.instantiate(): Import #1 module="i" function="jn9q" error: function import requires a callable.
```
And my URL is "http://127.0.0.1:8080/Cheepj_test.html", using Chrome.
my steps seems no difference with the steps in Tutorial...can anyone help me with that?

**Comment by alexp-sssup** [comment]
I just tested the tutorial and it works as expected. A few things to check.

1) Make sure you are using the same version of CheerpJ for the AOT compiler and the runtime. For example, the CheerpJ 2.1 AOT compiler must be only used with https://cjrtnc.leaningtech.com/2.1/loader.js
2) Make sure you follow the tutorial steps and copy code verbatim from the wiki. The ```cheerpjRunJar``` command you are using has various problems. This is the expected code from the Wiki: ```cheerpjRunJar("/app/TextDemo.jar"); ```
3) If these does not help, please publish the actual HTML code you are using somewhere, so that we can take a look. Also, what browser are you using?

**Comment by alexp-sssup** [comment]
Closing this bug due to lack of information.
