### ISSUE TITLE
Uncaught ReferenceError in rt.jar.sun.reflect.js

### ISSUE THREAD

**Issue by bartlomiej-kfn** [leaningtech/cheerpj-meta#86]
**CheerpJ version: 2.1
JDK version: 1.8.0_161**

Hi, I have project which use optaplanner library, it's a maven project which creates fat-jar executable will all dependencies.
It's compiled with `cheerpjfy.py droolstest.jar`. When I execute it with `java -jar droolstest.jar` it works fine, ending with success message after about  one minute. But when I execute it in CheerpJ as(
**java.vm.vendor** is mandatory for one dependency):

```
  cheerpjInit({
                javaProperties: [
                    "java.vm.vendor=IBM"
                ]
            }).then(function() {
                cheerpjRunMain("com.krakfin.pbz.plek.algorytm.Main", "/app/droolstest.jar");
            });
```
i get:
```

loader.js:401 Uncaught ReferenceError: _c4pbMJatyk$jWesfHjX0HZGMGaHKKtKiZZYostLJcbT3nE is not defined
    at ec4pbMJatyk$jWesfHjX0HZGMGaHKKtKiZZYostLJcbT3n (rt.jar.sun.reflect.js:190)
    at cheerpjThrow (loader.js:2247)
    at Object.eval [as func] (eval at buildContinuations (loader.js:115), <anonymous>:3:103)
    at runContinuationStack (loader.js:387)
    at cheerpjSchedule (loader.js:1110)
    at IFrameProxyDownloader.dl.onload (cheerpOS.js:389)
    at MessagePort.ipfMessage (loader.js:3524)
```
I include this sample project below.

[drools_test.zip](https://github.com/leaningtech/cheerpj-meta/files/4994486/drools_test.zip)

**Comment by alexp-sssup** [comment]
This is most likely a known bug in CheerpJ 2.1, which has already been fixed in the master branch. The fix will be included in the next release, due after the summer. It is our policy not to provide nightly builds of CheerpJ to non-commercial users. In case you are interested in acquiring a license please contact sales@leaningtech.com

In the mean time you proceed by using a recent runtime build (for example: https://cjrtnc.leaningtech.com/20200727/loader.js)

Please note that this runtime is _not_ compatible with the CheerpJ 2.1 AOT compiler, but you can still test your code by _not_ generating the jar.js at all. The CheerpJ runtime will build the code on-the-fly as required.

The resulting code will be much slower than the one coming from the AOT compiler, but it could be sufficient for testing.

I have actually tested the archive with the runtime build linked above and I can confirm that it works.
