### ISSUE TITLE
Cannot click/select/scroll/copy/paste in the text area

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#96]
For ImageJ.JS (https://ij.imjoy.io), we have a text editor built-in (click File -> New -> Text Window), the interaction using keyboard is working except copy and paste (CTRL-C + CTRL-V), and it doesn't respond to mouse click, drag to select, nor scroll with mouse wheel. 

Since these are very basic operation for a GUI, lack of them significantly decrease user experience.  Any idea for the fix? Is there a way to allow sending events to java event listeners?

**Comment by oeway** [comment]
I had to do some hacking to bypass some mouse event for the textarea elements:
```javascript
  const elm = cheerpjCreateDisplay(-1, -1, appContainer);
  const _addEL = elm.addEventListener
  elm.addEventListener = (event, handler)=>{
    if(event.startsWith('mouse') || event === 'contextmenu'){
      _addEL(event, (e)=>{
        // skip handling mouse events for textarea elements
        if(e.target.nodeName !== 'TEXTAREA'){
          handler(e)
        }
      })
    } 
    else
      _addEL(event, handler)
  }
```
I will take this hacky solution for now, would be nice to have an official fix for this issue.

For CTRL-C and CTRL-V, copy with right click to work, I need to also set `clipboardMode: "java"` when calling `cheerpjInit`.

**Comment by alexp-sssup** [comment]
click/select/scroll -> should be fixed with this endpoint: https://cjrtnc.leaningtech.com/20201025/loader.js

context menu -> native Java does not offer a context menu on AWT TextArea, so we think our implementation is correct by disabling it

copy/paste: Since ImageJ is a pure-AWT application your current workaround of setting ```clipboardMode:"java"``` should work fine, so I am closing this bug. The reality is that currently AWT is not integrated into the Java clipboard system and eventually we will need to engineer a full solution to this problem. When we do you will need to switch to ```clipboardMode:"system"```, but please be aware that the UX will be a little different in this mode. See here for more information: https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API#clipboardmode

**Comment by oeway** [comment]
Thanks!

About the context menu, from the user perspective, I think it would be nice to enable it. When seeing a text field in the browser, the user would expect that they can right click to get the context menu, for example, to "Search Google" for selected text.
